### ISSUE TITLE
Negative number of primaries in coin

### ISSUE THREAD

**Issue by ThWester** [mppmu/gerda-mage-sim#14]
Components: Minishroud (combined only)
Isotope: K40, Bi212

**Comment by ThWester** [comment]
already fixed.

type of nPrimEdep/nPrimCoin was int instead of long.

**Comment by gipert** [comment]
Great, if you are sure that `minishroud/K40` and `minishroud/Bi212` are the only affected I can reprocess only them, otherwise I can start a `v0.4.1` or so cycle.

**Comment by ThWester** [comment]
Its all of the minishroud. Only K40 and Bi212 show up as negative, the others just show some other random number.
The cables seem to be fine, because the number of primaries is not so high.

**Comment by ThWester** [comment]
@gipert Also, the number of primaries is 0 for cables/sig_cables/Tl208/pdf-cables-sig_cables-Tl208.root.
The other cable components/isotopes seem to be fine.
This is not the combined component, so it's a different problem. I don't know what causes this :/

**Comment by gipert** [comment]
Also, I still get weird (kinda random) values of `NumberOfPrimariesCoin` after your fix in `pdf-gen-volume`, I'll look into this more deeply

**Comment by annkasch** [comment]
There are some simulations missing:

- [ ] Pb-214 on the n+ surface

- [ ] Tl-208 in the mini shroud

**Comment by gipert** [comment]
Oh sorry, I meant #13

**Comment by gipert** [comment]
I think the number of primaries reported in the global pdf- file is correct, the wrong thing is the number  of simulated events in each part of the minishroud. This can be observed just from the READMEs, `minishroud-bottoms-Ac228-coin` has 4552997x100 primaries while `minishroud-tubs-Ac228-coin` has only 4552997x10, this results in a not uniform primaries distributions in the minishroud simulations @BirgitSchneider

**Comment by BirgitSchneider** [comment]
I don't quite get how this results in a not uniform primaries distribution.
In the case of Ac228 the primaries in minishroud are as following:
bottoms: 4 552 997 x 100
glue_rings_bottom: 7 018 237 x 100
glue_rings_top: 6 967 972 x 100
tops: 4 536 687 x 100
tubs: 76 924 104 x 10
It is obvious why for the tubs the primaries don't have to be increased by a factor of 100, and a factor of 10 is sufficient. If you would increase this by a factor of 100, you will need much more computing power and disk space than really neccessary.
So when adding up the simulations, you read the number of primaries in each root file and then normalize by the factor with which you increased the number of primaries, like that:
bottoms/100 + ... + tubs/10 
I don't know how you are doing it now, but it sounds, that you assumed, that the increasement factor should be the same for each part, which does not make sense to me, since the original number of primaries are quite different from each other (more than a factor 10).

Cheers, 
Birgit

**Comment by gipert** [comment]
Well, with the current implementation of the post-processing this situation produces a non-uniform distribution (because we don't normalise PDFs by the number of primaries) but the approach you suggested has some cons, imho. The pro of not normalising by the number of simulated events is that in the end you still have histograms with *true* counts, and this in principle is more flexible if you want to further play with the PDFs. Furthermore, you have to be concerned that, unless you don't have very high statistics in each part, you will introduce abnormal statistical fluctuations in your PDF, as e.g. you are adding together a PDF for N events in the tubs and Nx10 events in the bottoms.

However, doing such an event partition is motivated by the fact that in the background modelling we always fit cables and minishroud all together, and so in the end we only care about statistics in the "global" PDF, do you need to keep the minishroud parts separate for your purposes? If yes we can try to get to a better solution, for sure the current one is not optimal in this sense.

**Comment by BirgitSchneider** [comment]
I see your point. But I also think if you only check the statistics for the volume in total and not each part itself, that it can happen, that you have bad statistics in one part, which you want to prevent, right? Maybe the easiest way would be to multiply the primaries by 10 for tubs (as well as the histrogram counts). Then you should get uniform distributions and we don't simulate more than neccessary. Would this solve the problem with small effort?

However, I would not like it to decrease the primaries in bottoms & co., because then only in tubs the statistics would be fine. Then we could be dependent on statiscal fluctuations in all parts except tubs.

Cheers, 
Birgit

**Comment by vonsturm** [comment]
Ok so the point here is @BirgitSchneider you are right probably x100 for the tubs is too much but the internal weighting of the components here is critical for pdf production. We can either do x100 for all parts of the MS or x10... Do you think a down grade of all MS components to a statistics of x10 of the original one can be sufficient?

**Comment by vonsturm** [comment]
Ok this should be fixed... cf1fc03 fa07afd c67b60d 0b87517 c2549aa

**Comment by BirgitSchneider** [comment]
Thanks @gipert for all the explanations.
Thanks @vonsturm for fixing this. I had a look at the new README.md and I think in this way the statistics for the minishroud should be fine. Since only the global pdf's are important, for some nuclides the statiscs can be reduced to *1 instead of *10 in minishroud:
Ac288 *10
Bi212 * 10
Bi214 *10 -> *1 shoud by sufficient
K40 *10
Pa234m *10 -> *1 shoud by sufficient
Tl208 *1 (definitely sufficient)

I will have a look the the other volumes, since I probably made this mistake there as well. Sorry for the inconveniences.

Cheers, 
Birgit

**Comment by vonsturm** [comment]
I think for Bi214 and Pa234m we can leave it like it is now. More stats don't hurt :)

**Comment by vonsturm** [comment]
PS: Let me know if I can help fix something. In the evening I can do that.

**Comment by ThWester** [comment]
Thanks!

> Also, the number of coin primaries is 0 for cables/sig_cables/Tl208/pdf-cables-sig_cables-Tl208.root.
The other cable components/isotopes seem to be fine.
This is not the combined component, so it's a different problem. I don't know what causes this :/

Has this also been fixed? This seems not related to any of the other bugs.

**Comment by BirgitSchneider** [comment]
> I think for Bi214 and Pa234m we can leave it like it is now. More stats don't hurt :)
True :D

Is it right, that global pdf's are only created for cables and minishroud? So in all the other volumes there is no problem with changing primaries? 
The primaries in cables are increased equally in all parts, I just checked them. :)

@ThWester I don't see any problems in the macros or simulations in this case. In the output files are some warnings, but we already discussed this and there seem to be no actual effect from them.

**Comment by BirgitSchneider** [comment]
Okay, Luigi already simulated raw-cables-sig_cables-Tl208-coin-003.root again.
The problem was in this file, probably the simulation crashed shortly before finishing. It's weird that I didn't got any errors when checking statistics.

**Comment by gipert** [comment]
>>Also, the number of coin primaries is 0 for cables/sig_cables/Tl208/pdf-cables-sig_cables-Tl208.root.
The other cable components/isotopes seem to be fine.
This is not the combined component, so it's a different problem. I don't know what causes this :/

>Has this also been fixed? This seems not related to any of the other bugs.

Yes, there was some problems in the corresponding tier4ized files

**Comment by vonsturm** [comment]
@annkasch @ThWester please check and close the issue if everything is fine. new pdfs will be uploaded soon by @gipert

**Comment by gipert** [comment]
Still negative `NumberOfPrimaries` for `lar/sur_array/K42`, should we use a `double` to save ourselves the hassle?

**Comment by ThWester** [comment]
Are you on a 32bit machine? Because otherwise long should have been sufficient.
Anyway, long long should be save for sure.

**Comment by gipert** [comment]
Well, as we are running jobs on a potentially heterogeneous cluster we generally don't know, one in principle should know what's the composition of the pool of machines (which I don't). We should go for a conservative solution, why not using double-precision floating point?

**Comment by gipert** [comment]
Well, at the end it's the same, I'll change it to `unsigned long long int`

**Comment by gipert** [comment]
see 3784ed4

**Comment by gipert** [comment]
Changed every `NumberOfPriamaries` type to `Long64_t`, see 7948477, checked in the newest version of the PDFs
