### ISSUE TITLE
 ge_holders/plates/Ac228/coin macros missing

### ISSUE THREAD

**Issue by vonsturm** [mppmu/gerda-mage-sim#18]
ge_holders/plates/Ac228/coin

last root file:
raw-ge_holders-plates-Ac228-coin-099.root
last macro file:
raw-ge_holders-plates-Ac228-coin-009.mac
last log file:
raw-ge_holders-plates-Ac228-coin-099.out

@Birgit I think you made more simulations here than there are macros uploaded. We have root files with no corresponding macros. Could you check and open a pull request when you find them?

**Comment by BirgitSchneider** [comment]
I only created 10 macros in this case. The simulations are from you and they are older than my macros. I noticed that in the 10 macros from you, you set /MG/output/saveOnlyEventsWithEnergyDeposit false, however I have it "true" for all simulation. According to @ThWester this should cause no differences. In order to match the simulations I put it "false" for the missing macros.
Note that the macros have a newer time stamp than the simulations.

Cheers, 
Birgit
