### ISSUE TITLE
Set 40keV AC threshold?

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#3]
Up to now our AC threshold is 150keV (see [default Tier4izer settings](https://github.com/wiesinger-ch/gerda-metadata/blob/8b1ac5f634af3ed1526d7213791316ea23d78b5a/detector-data/ged-settings-default.json)), we should decide what threshold to use and apply it equally to data and PDFs. @ThWester

**Comment by wiesinger-ch** [comment]
Ciao @gipert ,
the default in that json file is 10 keV (offlineThreshold).
The default without loading any json is 40keV (https://github.com/mppmu/gerda-ada/blob/master/src/tier4izer/T4SimChannel.h#L31).

I guess also an individual threshold per detector should be not too difficult to extract and easy to handle via the json.

**Comment by ThWester** [comment]
Just transfering my comment from the email to here:

As far as I understand the T4izer, the 150keV online threshold is the trigger threshold:
https://github.com/mppmu/gerda-ada/blob/9a46747cd9b5eb4c36900a86e85bf8a8cae41e68/src/tier4izer/T4SimGedEvent.cxx#L58

--> sets tgd (trigger detector? ) to true, and only if true the event is left as is (L66), energies and multiplicity is set to 0.

The AC threshold is the 'offline threshold' of 10keV.

Because the detectors have varying threshold from 10 to 40keV, that causes trouble if we want to compare data and MC, because such events can enter relevant regions (e.g. E1=1505keV, E2=20keV).
So a 40keV threshold should be applied to MC and data for coincidence events.

**Comment by ThWester** [comment]
Instead of energy>0 and energy<10000, we can just add energy>40 and energy<10000 in the pdf-gen script and use basically the same script for the generation of the data histograms (which is what I did for my first test fits).
This excludes some multiplicity==2 events from the data (without adding them to the AC data). Multiplicity>2 will be neglected, unless we recalculate the mulitplicity given the new threshold. Not necessary in my opinion though, because the ratio of such events is very small.

**Comment by gipert** [comment]
@wiesinger-ch yes, sorry, stupid typo... So I guess we can set 40keV as the `offlineThreshold` in the Tier4izer and the same in the script that will produce the data energy spectra (`data-gen`?)

**Comment by gipert** [comment]
Implemented in 8d46f8f.

**Comment by wiesinger-ch** [comment]
Ciao, just for curiosity: Why do you add the AC threshold in https://github.com/mppmu/gerda-mage-sim/commit/8d46f8ff1d88d5850b90598fc6502876dac40033.
After "tier4ization" there is anyhow now events <40 keV should pop up.

https://github.com/mppmu/gerda-mage-sim/blob/master/UTILS/post/pdf-gen.cxx#L227
This exception will happen. Triggering events in AC detectors get the energy 10000 assigned.

**Comment by gipert** [comment]
> Triggering events in AC detectors get the energy 10000 assigned.

mmh right, so the `energy[i] < 10000` instruction actually removes events from AC detectors, right? I guess I can simply remove it then. Setting `energy[i] < 40` here in `pdf-gen` or setting it in the Tier4izer json file should produce the same result in the end, is it correct?

**Comment by wiesinger-ch** [comment]
> mmh right, so the energy[i] < 10000 instruction actually removes events from AC detectors, right? I guess I can simply remove it then. Setting energy[i] > 40 here in pdf-gen or setting it in the Tier4izer json file should produce the same result in the end, is it correct?

yes and yes :)
I would leave the threshold to the tier4izer.
We could then think about checking the background model for the 0nbb-no-AC-threshold-case by passing the intrinsic QC thresholds as meta data to the full tier4izing/pdf-bulding machinery.

**Comment by gipert** [comment]
Just pushed 878850e, what do you think?

**Comment by wiesinger-ch** [comment]
Yes, I guess this should do the job.

**Comment by gipert** [comment]
I'll test it a bit this afternoon
